<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328130445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE reservations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reclamations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_documents_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_offers_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE associations_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voyage_images_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE offer_views_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refund_requests_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE promo_codes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_logins_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE search_history_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE voyage_visits_id_seq CASCADE');
        $this->addSql('ALTER TABLE admins DROP CONSTRAINT admins_user_id_fkey');
        $this->addSql('ALTER TABLE offer_views DROP CONSTRAINT offer_views_offer_id_fkey');
        $this->addSql('ALTER TABLE offer_views DROP CONSTRAINT offer_views_user_id_fkey');
        $this->addSql('ALTER TABLE promo_codes DROP CONSTRAINT promo_codes_offer_id_fkey');
        $this->addSql('ALTER TABLE reclamations DROP CONSTRAINT reclamations_reservation_id_fkey');
        $this->addSql('ALTER TABLE reclamations DROP CONSTRAINT reclamations_user_id_fkey');
        $this->addSql('ALTER TABLE refund_requests DROP CONSTRAINT refund_requests_reclamation_id_fkey');
        $this->addSql('ALTER TABLE refund_requests DROP CONSTRAINT refund_requests_requester_id_fkey');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT reservations_voyage_id_fkey');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT reservations_offer_id_fkey');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT reservations_user_id_fkey');
        $this->addSql('ALTER TABLE search_history DROP CONSTRAINT search_history_user_id_fkey');
        $this->addSql('ALTER TABLE user_associations DROP CONSTRAINT user_associations_association_id_fkey');
        $this->addSql('ALTER TABLE user_associations DROP CONSTRAINT user_associations_user_id_fkey');
        $this->addSql('ALTER TABLE user_documents DROP CONSTRAINT user_documents_user_id_fkey');
        $this->addSql('ALTER TABLE user_logins DROP CONSTRAINT user_logins_user_id_fkey');
        $this->addSql('ALTER TABLE user_offers DROP CONSTRAINT user_offers_offer_id_fkey');
        $this->addSql('ALTER TABLE user_offers DROP CONSTRAINT user_offers_user_id_fkey');
        $this->addSql('ALTER TABLE voyage_images DROP CONSTRAINT voyage_images_voyage_id_fkey');
        $this->addSql('ALTER TABLE voyage_visits DROP CONSTRAINT voyage_visits_user_id_fkey');
        $this->addSql('ALTER TABLE voyage_visits DROP CONSTRAINT voyage_visits_voyage_id_fkey');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE associations');
        $this->addSql('DROP TABLE offer_views');
        $this->addSql('DROP TABLE promo_codes');
        $this->addSql('DROP TABLE reclamations');
        $this->addSql('DROP TABLE refund_requests');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE search_history');
        $this->addSql('DROP TABLE user_associations');
        $this->addSql('DROP TABLE user_documents');
        $this->addSql('DROP TABLE user_logins');
        $this->addSql('DROP TABLE user_offers');
        $this->addSql('DROP TABLE voyage_images');
        $this->addSql('DROP TABLE voyage_visits');
        $this->addSql('ALTER TABLE activities DROP type');
        $this->addSql('ALTER TABLE activities DROP location');
        $this->addSql('ALTER TABLE activities DROP is_available');
        $this->addSql('ALTER TABLE activities DROP created_at');
        $this->addSql('ALTER TABLE activities DROP updated_at');
        $this->addSql('ALTER TABLE activities ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE activities ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE activities ALTER price_per_person DROP DEFAULT');
        $this->addSql('ALTER TABLE activities ALTER price_per_person SET NOT NULL');
        $this->addSql('DROP INDEX idx_offers_active');
        $this->addSql('ALTER TABLE offers DROP created_at');
        $this->addSql('ALTER TABLE offers DROP updated_at');
        $this->addSql('ALTER TABLE offers DROP destination_name');
        $this->addSql('ALTER TABLE offers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE offers ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE offers ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER TABLE offers ALTER is_active SET NOT NULL');
        $this->addSql('ALTER TABLE offers ALTER voyage_id SET NOT NULL');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX users_email_key RENAME TO UNIQ_1483A5E9E7927C74');
        $this->addSql('ALTER TABLE voyages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE voyages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE voyages ALTER image_url TYPE JSON USING CASE WHEN image_url IS NOT NULL THEN json_build_array(image_url) ELSE NULL END');
        $this->addSql('ALTER TABLE voyages ALTER created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE reservations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reclamations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_documents_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_offers_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE associations_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voyage_images_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE offer_views_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refund_requests_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE promo_codes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_logins_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE search_history_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE voyage_visits_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE admins (user_id INT NOT NULL, access_level INT DEFAULT 1, PRIMARY KEY (user_id))');
        $this->addSql('CREATE TABLE associations (id INT DEFAULT nextval(\'associations_id_seq\'::regclass) NOT NULL, name VARCHAR(255) NOT NULL, company_code VARCHAR(50) NOT NULL, discount_rate NUMERIC(5, 2) DEFAULT \'0.00\', PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX associations_company_code_key ON associations (company_code)');
        $this->addSql('CREATE TABLE offer_views (id INT DEFAULT nextval(\'offer_views_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, offer_id INT NOT NULL, view_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, clicked BOOLEAN DEFAULT false, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_offer_views_time ON offer_views (view_time)');
        $this->addSql('CREATE INDEX idx_offer_views_clicked ON offer_views (clicked)');
        $this->addSql('CREATE INDEX idx_offer_views_offer_id ON offer_views (offer_id)');
        $this->addSql('CREATE INDEX idx_offer_views_user_id ON offer_views (user_id)');
        $this->addSql('CREATE TABLE promo_codes (id INT DEFAULT nextval(\'promo_codes_id_seq\'::regclass) NOT NULL, code VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, offer_id INT NOT NULL, valid_from DATE NOT NULL, valid_to DATE NOT NULL, usage_limit INT DEFAULT 1 NOT NULL, used_count INT DEFAULT 0 NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX promo_codes_code_key ON promo_codes (code)');
        $this->addSql('CREATE INDEX IDX_C84FDDB53C674EE ON promo_codes (offer_id)');
        $this->addSql('CREATE TABLE reclamations (id INT DEFAULT nextval(\'reclamations_id_seq\'::regclass) NOT NULL, reservation_id INT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, reclamation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) DEFAULT \'OPEN\', priority VARCHAR(10) DEFAULT \'MEDIUM\', admin_response TEXT DEFAULT NULL, response_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolution_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reclamations_status ON reclamations (status, priority)');
        $this->addSql('CREATE INDEX IDX_1CAD6B76B83297E7 ON reclamations (reservation_id)');
        $this->addSql('CREATE INDEX IDX_1CAD6B76A76ED395 ON reclamations (user_id)');
        $this->addSql('CREATE TABLE refund_requests (id INT DEFAULT nextval(\'refund_requests_id_seq\'::regclass) NOT NULL, reclamation_id INT NOT NULL, requester_id INT NOT NULL, amount NUMERIC(10, 2) NOT NULL, reason TEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'PENDING\', created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, translated_reason TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A6AE4522D6BA2D9 ON refund_requests (reclamation_id)');
        $this->addSql('CREATE INDEX IDX_A6AE452ED442CF4 ON refund_requests (requester_id)');
        $this->addSql('CREATE TABLE reservations (id INT DEFAULT nextval(\'reservations_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, voyage_id INT NOT NULL, offer_id INT DEFAULT NULL, reservation_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, number_of_people INT NOT NULL, total_price NUMERIC(10, 2) NOT NULL, status VARCHAR(20) DEFAULT \'PENDING\', special_requests TEXT DEFAULT NULL, payment_status VARCHAR(20) DEFAULT \'PENDING\', payment_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_reservations_status ON reservations (status, reservation_date)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_voyage ON reservations (user_id, voyage_id)');
        $this->addSql('CREATE INDEX idx_reservations_user ON reservations (user_id)');
        $this->addSql('CREATE INDEX IDX_4DA23968C9E5AF ON reservations (voyage_id)');
        $this->addSql('CREATE INDEX IDX_4DA23953C674EE ON reservations (offer_id)');
        $this->addSql('CREATE TABLE search_history (id INT DEFAULT nextval(\'search_history_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, search_query VARCHAR(255) NOT NULL, search_type VARCHAR(50) NOT NULL, search_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, results_found INT DEFAULT 0, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_search_history_user_id ON search_history (user_id)');
        $this->addSql('CREATE INDEX idx_search_history_time ON search_history (search_time)');
        $this->addSql('CREATE INDEX idx_search_history_query ON search_history (search_query)');
        $this->addSql('CREATE INDEX idx_search_history_type ON search_history (search_type)');
        $this->addSql('CREATE TABLE user_associations (user_id INT NOT NULL, association_id INT DEFAULT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE INDEX IDX_9EDB8B3EFB9C8A5 ON user_associations (association_id)');
        $this->addSql('CREATE TABLE user_documents (id INT DEFAULT nextval(\'user_documents_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, nationality VARCHAR(100) DEFAULT NULL, passport_number VARCHAR(255) DEFAULT NULL, passport_expiry_date DATE DEFAULT NULL, cin_number VARCHAR(255) DEFAULT NULL, cin_creation_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A250FF6CA76ED395 ON user_documents (user_id)');
        $this->addSql('CREATE TABLE user_logins (id INT DEFAULT nextval(\'user_logins_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, login_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, login_method VARCHAR(50) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_logins_time ON user_logins (login_time)');
        $this->addSql('CREATE INDEX idx_user_logins_method ON user_logins (login_method)');
        $this->addSql('CREATE INDEX idx_user_logins_user_id ON user_logins (user_id)');
        $this->addSql('CREATE TABLE user_offers (id INT DEFAULT nextval(\'user_offers_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, offer_id INT NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, status VARCHAR(20) DEFAULT \'ACTIVE\', PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_user_offers_user ON user_offers (user_id)');
        $this->addSql('CREATE UNIQUE INDEX user_offers_user_id_offer_id_key ON user_offers (user_id, offer_id)');
        $this->addSql('CREATE INDEX IDX_BF141F1A53C674EE ON user_offers (offer_id)');
        $this->addSql('CREATE TABLE voyage_images (id INT DEFAULT nextval(\'voyage_images_id_seq\'::regclass) NOT NULL, voyage_id INT NOT NULL, image_url VARCHAR(500) NOT NULL, cloudinary_public_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D0A0D1BF68C9E5AF ON voyage_images (voyage_id)');
        $this->addSql('CREATE TABLE voyage_visits (id INT DEFAULT nextval(\'voyage_visits_id_seq\'::regclass) NOT NULL, user_id INT NOT NULL, voyage_id INT NOT NULL, visit_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, source VARCHAR(50) DEFAULT \'direct\', view_duration_seconds INT DEFAULT 0, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_voyage_visits_voyage_id ON voyage_visits (voyage_id)');
        $this->addSql('CREATE INDEX idx_voyage_visits_time ON voyage_visits (visit_time)');
        $this->addSql('CREATE INDEX idx_voyage_visits_user_id ON voyage_visits (user_id)');
        $this->addSql('CREATE INDEX idx_voyage_visits_source ON voyage_visits (source)');
        $this->addSql('ALTER TABLE admins ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_views ADD CONSTRAINT offer_views_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE offer_views ADD CONSTRAINT offer_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_codes ADD CONSTRAINT promo_codes_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reclamations ADD CONSTRAINT reclamations_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES reservations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reclamations ADD CONSTRAINT reclamations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund_requests ADD CONSTRAINT refund_requests_reclamation_id_fkey FOREIGN KEY (reclamation_id) REFERENCES reclamations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refund_requests ADD CONSTRAINT refund_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT reservations_voyage_id_fkey FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT reservations_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE search_history ADD CONSTRAINT search_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_associations ADD CONSTRAINT user_associations_association_id_fkey FOREIGN KEY (association_id) REFERENCES associations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_associations ADD CONSTRAINT user_associations_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_documents ADD CONSTRAINT user_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_logins ADD CONSTRAINT user_logins_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_offers ADD CONSTRAINT user_offers_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES offers (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_offers ADD CONSTRAINT user_offers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voyage_images ADD CONSTRAINT voyage_images_voyage_id_fkey FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voyage_visits ADD CONSTRAINT voyage_visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voyage_visits ADD CONSTRAINT voyage_visits_voyage_id_fkey FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activities ADD type VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE activities ADD location VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE activities ADD is_available BOOLEAN DEFAULT true');
        $this->addSql('ALTER TABLE activities ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE activities ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE activities ALTER id SET DEFAULT nextval(\'activities_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE activities ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE activities ALTER price_per_person SET DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE activities ALTER price_per_person DROP NOT NULL');
        $this->addSql('ALTER TABLE offers ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE offers ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE offers ADD destination_name VARCHAR(255) DEFAULT \'\' NOT NULL');
        $this->addSql('ALTER TABLE offers ALTER id SET DEFAULT nextval(\'offers_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE offers ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE offers ALTER is_active SET DEFAULT true');
        $this->addSql('ALTER TABLE offers ALTER is_active DROP NOT NULL');
        $this->addSql('ALTER TABLE offers ALTER voyage_id DROP NOT NULL');
        $this->addSql('CREATE INDEX idx_offers_active ON offers (is_active, end_date)');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO users_email_key');
        $this->addSql('ALTER TABLE voyages ALTER id SET DEFAULT nextval(\'voyages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE voyages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE voyages ALTER image_url TYPE VARCHAR(500) USING image_url->>0');
        $this->addSql('ALTER TABLE voyages ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
    }
}
