<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507231336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE favorites DROP CONSTRAINT IF EXISTS fk_favorites_voyage');
        $this->addSql('ALTER TABLE favorites DROP CONSTRAINT IF EXISTS fk_favorites_user');
        $this->addSql('DROP INDEX IF EXISTS IDX_E46960F568C9E5AF');
        $this->addSql('DROP INDEX IF EXISTS IDX_E46960F5A76ED395');
        $this->addSql('ALTER TABLE favorites ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE favorites ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE favorites ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE favorites ALTER created_at DROP DEFAULT');
        $this->addSql('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = \'unique_favorite\') THEN EXECUTE \'ALTER INDEX unique_favorite RENAME TO uniq_user_voyage\'; END IF; END $$');
        $this->addSql('ALTER TABLE loyalty_points DROP CONSTRAINT IF EXISTS fk_loyalty_user');
        $this->addSql('ALTER TABLE loyalty_points ADD points_balance INT NOT NULL');
        $this->addSql('ALTER TABLE loyalty_points DROP points');
        $this->addSql('ALTER TABLE loyalty_points ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_points ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at SET NOT NULL');
        $this->addSql('DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = \'loyalty_points_user_id_key\') THEN EXECUTE \'ALTER INDEX loyalty_points_user_id_key RENAME TO UNIQ_E0C7D07DA76ED395\'; END IF; END $$');
        $this->addSql('ALTER TABLE offer_views ALTER view_time TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE offers ADD flash_sale_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE offers ADD flash_sale_discount NUMERIC(5, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE offers ALTER start_date SET NOT NULL');
        $this->addSql('ALTER TABLE offers ALTER end_date SET NOT NULL');
        $this->addSql('ALTER TABLE reclamations ADD response_deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE reclamations ALTER reclamation_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER response_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER resolution_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE refund_requests ADD reservation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE refund_requests ADD approved_amount NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE refund_requests ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reservations ADD payment_reference VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE reservations ALTER reservation_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reservations ALTER payment_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reservations ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS fk_reviews_user');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS fk_reviews_voyage');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT IF EXISTS unique_review');
        $this->addSql('DROP INDEX IF EXISTS IDX_6970EB0FA76ED395');
        $this->addSql('DROP INDEX IF EXISTS IDX_6970EB0F68C9E5AF');
        $this->addSql('ALTER TABLE reviews ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reviews ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE reviews ALTER rating TYPE SMALLINT');
        $this->addSql('ALTER TABLE reviews ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE reviews ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE reviews ALTER created_at SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uq_review_user_voyage ON reviews (user_id, voyage_id)');
        $this->addSql('DROP VIEW IF EXISTS unified_events');
        $this->addSql('ALTER TABLE search_history ALTER search_time TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tags ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tags ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE user_documents ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_documents ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_offers ALTER claimed_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE voyage_images ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE voyage_images ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE voyage_visits ALTER visit_time TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE user_logins ALTER login_time TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('CREATE OR REPLACE VIEW unified_events AS SELECT voyage_visits.id, voyage_visits.user_id, \'voyage_visits\'::text AS type, voyage_visits.visit_time AS created_at, jsonb_build_object(\'voyage_id\', voyage_visits.voyage_id, \'source\', voyage_visits.source, \'duration\', voyage_visits.view_duration_seconds) AS data FROM voyage_visits UNION ALL SELECT search_history.id, search_history.user_id, \'search\'::text AS type, search_history.search_time AS created_at, jsonb_build_object(\'query\', search_history.search_query, \'type\', search_history.search_type, \'results\', search_history.results_found) AS data FROM search_history UNION ALL SELECT user_logins.id, user_logins.user_id, \'login\'::text AS type, user_logins.login_time AS created_at, jsonb_build_object(\'method\', user_logins.login_method, \'ip\', user_logins.ip_address) AS data FROM user_logins');
        $this->addSql('ALTER TABLE voyages ADD slug VARCHAR(255) DEFAULT \'\' NOT NULL');
        $this->addSql('UPDATE voyages SET slug = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(title, \'[^a-zA-Z0-9 ]\', \'\', \'g\'), \' +\', \'-\', \'g\')) || \'-\' || id WHERE slug = \'\'');
        $this->addSql('ALTER TABLE voyages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_30F7F9989D9B62 ON voyages (slug)');
        $this->addSql('ALTER TABLE waitlist_entries DROP CONSTRAINT IF EXISTS fk_waitlist_voyage');
        $this->addSql('ALTER TABLE waitlist_entries DROP CONSTRAINT IF EXISTS fk_waitlist_user');
        $this->addSql('ALTER TABLE waitlist_entries DROP CONSTRAINT IF EXISTS unique_waitlist');
        $this->addSql('DROP INDEX IF EXISTS unique_waitlist');
        $this->addSql('DROP INDEX IF EXISTS IDX_E74550EE68C9E5AF');
        $this->addSql('DROP INDEX IF EXISTS IDX_E74550EEA76ED395');
        $this->addSql('ALTER TABLE waitlist_entries ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE waitlist_entries ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE waitlist_entries ALTER notified DROP DEFAULT');
        $this->addSql('ALTER TABLE waitlist_entries ALTER notified SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_voyage_waitlist ON waitlist_entries (user_id, voyage_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE favorites ALTER id SET DEFAULT nextval(\'favorites_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE favorites ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE favorites ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE favorites ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE favorites ADD CONSTRAINT fk_favorites_voyage FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE favorites ADD CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E46960F568C9E5AF ON favorites (voyage_id)');
        $this->addSql('CREATE INDEX IDX_E46960F5A76ED395 ON favorites (user_id)');
        $this->addSql('ALTER INDEX uniq_user_voyage RENAME TO unique_favorite');
        $this->addSql('ALTER TABLE loyalty_points ADD points INT DEFAULT 0');
        $this->addSql('ALTER TABLE loyalty_points DROP points_balance');
        $this->addSql('ALTER TABLE loyalty_points ALTER id SET DEFAULT nextval(\'loyalty_points_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loyalty_points ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE loyalty_points ALTER updated_at DROP NOT NULL');
        $this->addSql('ALTER TABLE loyalty_points ADD CONSTRAINT fk_loyalty_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_e0c7d07da76ed395 RENAME TO loyalty_points_user_id_key');
        $this->addSql('ALTER TABLE offer_views ALTER view_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE offers DROP flash_sale_ends_at');
        $this->addSql('ALTER TABLE offers DROP flash_sale_discount');
        $this->addSql('ALTER TABLE offers ALTER start_date DROP NOT NULL');
        $this->addSql('ALTER TABLE offers ALTER end_date DROP NOT NULL');
        $this->addSql('ALTER TABLE reclamations DROP response_deadline');
        $this->addSql('ALTER TABLE reclamations ALTER reclamation_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER response_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER resolution_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reclamations ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE refund_requests DROP reservation_id');
        $this->addSql('ALTER TABLE refund_requests DROP approved_amount');
        $this->addSql('ALTER TABLE refund_requests ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reservations DROP payment_reference');
        $this->addSql('ALTER TABLE reservations ALTER reservation_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reservations ALTER payment_date TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reservations ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('DROP INDEX uq_review_user_voyage');
        $this->addSql('ALTER TABLE reviews ALTER id SET DEFAULT nextval(\'reviews_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reviews ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE reviews ALTER rating TYPE INT');
        $this->addSql('ALTER TABLE reviews ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE reviews ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE reviews ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT fk_reviews_voyage FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX unique_review ON reviews (voyage_id, user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0FA76ED395 ON reviews (user_id)');
        $this->addSql('CREATE INDEX IDX_6970EB0F68C9E5AF ON reviews (voyage_id)');
        $this->addSql('ALTER TABLE search_history ALTER search_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE tags ALTER id SET DEFAULT nextval(\'tags_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tags ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE user_documents ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE user_documents ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE user_logins ALTER login_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE user_offers ALTER claimed_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE voyage_images ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE voyage_images ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE voyage_visits ALTER visit_time TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('DROP INDEX UNIQ_30F7F9989D9B62');
        $this->addSql('ALTER TABLE voyages DROP slug');
        $this->addSql('ALTER TABLE voyages ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('DROP INDEX uniq_user_voyage_waitlist');
        $this->addSql('ALTER TABLE waitlist_entries ALTER id SET DEFAULT nextval(\'waitlist_entries_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE waitlist_entries ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE waitlist_entries ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE waitlist_entries ALTER notified SET DEFAULT false');
        $this->addSql('ALTER TABLE waitlist_entries ALTER notified DROP NOT NULL');
        $this->addSql('ALTER TABLE waitlist_entries ADD CONSTRAINT fk_waitlist_voyage FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE waitlist_entries ADD CONSTRAINT fk_waitlist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX unique_waitlist ON waitlist_entries (voyage_id, user_id)');
        $this->addSql('CREATE INDEX IDX_E74550EE68C9E5AF ON waitlist_entries (voyage_id)');
        $this->addSql('CREATE INDEX IDX_E74550EEA76ED395 ON waitlist_entries (user_id)');
    }
}
