<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schema sync — all operations are idempotent.
 * loyalty_points and waitlist_entries were already created by Version20260423140000.
 */
final class Version20260423163953 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schema sync: flash-sale columns, identity columns, voyage_tags FK constraints';
    }

    public function up(Schema $schema): void
    {
        // Flash sale columns — already added by Version20260423140000, safe to skip
        $this->addSql('ALTER TABLE offers ADD COLUMN IF NOT EXISTS flash_sale_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE offers ADD COLUMN IF NOT EXISTS flash_sale_discount NUMERIC(5, 2) DEFAULT NULL');

        // favorites: switch id to IDENTITY (skip if already IDENTITY)
        $this->addSql("DO \$\$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='favorites' AND column_name='id'
                  AND column_default IS NULL AND identity_generation IS NOT NULL
            ) THEN
                ALTER TABLE favorites ALTER id DROP DEFAULT;
                ALTER TABLE favorites ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE favorites ALTER created_at DROP DEFAULT;
            END IF;
        END; \$\$");

        // tags: switch id to IDENTITY
        $this->addSql("DO \$\$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='tags' AND column_name='id'
                  AND identity_generation IS NOT NULL
            ) THEN
                ALTER TABLE tags ALTER id DROP DEFAULT;
                ALTER TABLE tags ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END; \$\$");

        // voyages slug: drop default (was '' from earlier migration)
        $this->addSql("DO \$\$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='voyages' AND column_name='slug' AND column_default IS NOT NULL
            ) THEN
                ALTER TABLE voyages ALTER slug DROP DEFAULT;
            END IF;
        END; \$\$");

        // Rename slug index if the old name still exists
        $this->addSql("DO \$\$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname='uniq_voyage_slug') THEN
                ALTER INDEX uniq_voyage_slug RENAME TO UNIQ_30F7F9989D9B62;
            END IF;
        END; \$\$");

        // voyage_tags FK constraints — add only if not already present
        $this->addSql("DO \$\$ BEGIN
            ALTER TABLE voyage_tags ADD CONSTRAINT FK_FF2E5CA868C9E5AF FOREIGN KEY (voyage_id) REFERENCES voyages (id) ON DELETE CASCADE;
        EXCEPTION WHEN duplicate_object THEN NULL; END; \$\$");

        $this->addSql("DO \$\$ BEGIN
            ALTER TABLE voyage_tags ADD CONSTRAINT FK_FF2E5CA8BAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;
        EXCEPTION WHEN duplicate_object THEN NULL; END; \$\$");

        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_FF2E5CA868C9E5AF ON voyage_tags (voyage_id)');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_FF2E5CA8BAD26311 ON voyage_tags (tag_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE offers DROP COLUMN IF EXISTS flash_sale_ends_at');
        $this->addSql('ALTER TABLE offers DROP COLUMN IF EXISTS flash_sale_discount');
        $this->addSql('DROP INDEX IF EXISTS IDX_FF2E5CA868C9E5AF');
        $this->addSql('DROP INDEX IF EXISTS IDX_FF2E5CA8BAD26311');
    }
}
